/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check — does not touch DB */
        get: operations["HealthController_liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness check — verifies DB connectivity */
        get: operations["HealthController_readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync the JWT-bearing user into local DB as CUSTOMER
         * @description Idempotent. The first call creates a `User` row keyed by the Supabase `sub`; subsequent calls refresh email/profile fields. The frontend should call this once after sign-in/sign-up before issuing any other authenticated request.
         */
        post: operations["AuthController_syncCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/admin/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync the JWT-bearing user as ADMIN (allowlist gated)
         * @description Same upsert as `/auth/sync` but elevates the user to ADMIN. Caller email must be in `ADMIN_EMAILS`; otherwise 403. Use this after admins log into the admin frontend.
         */
        post: operations["AuthController_syncAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the current user profile */
        get: operations["UsersController_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the current user profile */
        patch: operations["UsersController_updateMe"];
        trace?: never;
    };
    "/api/v1/destinations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active destinations (paginated) */
        get: operations["DestinationsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/destinations/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one active destination by slug */
        get: operations["DestinationsController_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/destinations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin: list all destinations (incl. drafts) */
        get: operations["AdminDestinationsController_list"];
        put?: never;
        /** Admin: create a destination */
        post: operations["AdminDestinationsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/destinations/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin: get one destination by slug */
        get: operations["AdminDestinationsController_detail"];
        put?: never;
        post?: never;
        /** Admin: delete a destination */
        delete: operations["AdminDestinationsController_remove"];
        options?: never;
        head?: never;
        /** Admin: partial update a destination */
        patch: operations["AdminDestinationsController_update"];
        trace?: never;
    };
    "/api/v1/tours": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List published tours (paginated, filterable) */
        get: operations["ToursController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tours/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one published tour by slug */
        get: operations["ToursController_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tours/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin: get one tour by slug (with destination) */
        get: operations["AdminToursController_detail"];
        put?: never;
        post?: never;
        /** Admin: delete a tour */
        delete: operations["AdminToursController_remove"];
        options?: never;
        head?: never;
        /** Admin: partial update a tour */
        patch: operations["AdminToursController_update"];
        trace?: never;
    };
    "/api/v1/admin/tours": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin: create a tour */
        post: operations["AdminToursController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tours/{slug}/itinerary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin: list itinerary days for a tour */
        get: operations["AdminItineraryController_list"];
        put?: never;
        /** Admin: create an itinerary day */
        post: operations["AdminItineraryController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tours/{slug}/itinerary/{dayNumber}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Admin: delete an itinerary day */
        delete: operations["AdminItineraryController_remove"];
        options?: never;
        head?: never;
        /** Admin: partial update an itinerary day */
        patch: operations["AdminItineraryController_update"];
        trace?: never;
    };
    "/api/v1/tours/{slug}/departures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List upcoming departures for a tour */
        get: operations["DeparturesController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tours/{slug}/departures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin: list departures (full history) */
        get: operations["AdminDeparturesController_list"];
        put?: never;
        /** Admin: create a departure */
        post: operations["AdminDeparturesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tours/{slug}/departures/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Admin: delete a departure */
        delete: operations["AdminDeparturesController_remove"];
        options?: never;
        head?: never;
        /** Admin: partial update a departure */
        patch: operations["AdminDeparturesController_update"];
        trace?: never;
    };
    "/api/v1/admin/uploads/signed-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin: compute a Cloudinary signed upload */
        post: operations["AdminUploadsController_createSignedUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stripe webhook receiver (signature-verified) */
        post: operations["PaymentsController_handle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a booking + Stripe Checkout session */
        post: operations["BookingsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Caller's bookings (newest first, top 50) */
        get: operations["BookingsController_listOwn"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one booking by code (owner or admin) */
        get: operations["BookingsController_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/bookings/{id}/refund": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refund a PAID booking (admin) */
        post: operations["AdminBookingsController_refund"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a review for one of caller's PAID bookings */
        post: operations["ReviewsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tours/{slug}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List approved reviews for a tour (paginated) */
        get: operations["PublicReviewsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reviews/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Approve or re-draft a review (admin) */
        patch: operations["AdminReviewsController_moderate"];
        trace?: never;
    };
    "/api/v1/wishlist/{tourId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a tour to caller's wishlist (idempotent) */
        post: operations["WishlistController_add"];
        /** Remove a tour from caller's wishlist (idempotent) */
        delete: operations["WishlistController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wishlist/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Caller's wishlist with joined tour previews */
        get: operations["WishlistController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard aggregates (revenue, top tours, trend) */
        get: operations["AdminStatsController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SyncUserDto: {
            /** @example Nguyen Van A */
            fullName?: string;
            /** @example +84901234567 */
            phone?: string;
            /**
             * @example en
             * @enum {string}
             */
            locale?: "en" | "vi";
        };
        UserDto: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description Supabase auth.users.id
             */
            supabaseId: string;
            /** Format: email */
            email: string;
            fullName: string | null;
            phone: string | null;
            /**
             * @example en
             * @enum {string}
             */
            locale: "en" | "vi";
            /**
             * @example CUSTOMER
             * @enum {string}
             */
            role: "CUSTOMER" | "ADMIN";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateMeDto: {
            /** @example Nguyen Van A */
            fullName?: string;
            /** @example +84901234567 */
            phone?: string;
            /** @enum {string} */
            locale?: "en" | "vi";
        };
        MediaItemDto: {
            /** Format: uri */
            url: string;
            /** @enum {string} */
            type: "IMAGE" | "VIDEO";
            /**
             * @example gallery
             * @enum {string}
             */
            role: "hero" | "gallery" | "avatar";
            /**
             * Format: uri
             * @description Video poster URL.
             */
            posterUrl?: string;
            width?: number | null;
            height?: number | null;
            durationSec?: number | null;
            /** @example 0 */
            sortOrder: number;
        };
        DestinationDto: {
            /** Format: uuid */
            id: string;
            /** @example ha-long-bay */
            slug: string;
            /** @example Ha Long Bay */
            nameEn: string;
            /** @example Vịnh Hạ Long */
            nameVi: string;
            /** @example Vietnam */
            country: string;
            region: string | null;
            descriptionEn: string | null;
            descriptionVi: string | null;
            isActive: boolean;
            /** @description Cloudinary-backed media (hero/gallery/video). */
            media: components["schemas"]["MediaItemDto"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ApiMetaDto: {
            /** @example 1 */
            page: number;
            /** @example 20 */
            pageSize: number;
            /** @example 42 */
            total: number;
            /** @example 3 */
            totalPages: number;
        };
        PaginatedDestinationsDto: {
            items: components["schemas"]["DestinationDto"][];
            meta: components["schemas"]["ApiMetaDto"];
        };
        MediaInputDto: {
            /**
             * @description Cloudinary public_id (no extension).
             * @example tourism/tours/hero/1717000000000-hoi-an
             */
            publicId: string;
            /**
             * @example IMAGE
             * @enum {string}
             */
            type: "IMAGE" | "VIDEO";
            /**
             * @example gallery
             * @enum {string}
             */
            role: "hero" | "gallery" | "avatar";
            /** @example jpg */
            format?: string;
            /** @example 1920 */
            width?: number;
            /** @example 1080 */
            height?: number;
            /**
             * @description Video duration in seconds (video only).
             * @example 12.5
             */
            durationSec?: number;
            /**
             * @description Dedicated poster image public_id (video only).
             * @example tourism/tours/video/1717000000000-poster
             */
            posterId?: string;
            /**
             * @description Display order.
             * @example 0
             */
            sortOrder?: number;
        };
        CreateDestinationDto: {
            /**
             * @description Any format — normalized server-side to kebab-case (max 80). Omit to generate from nameEn.
             * @example hoi-an
             */
            slug?: string;
            /** @example Hoi An */
            nameEn: string;
            /** @example Hội An */
            nameVi: string;
            /** @example Vietnam */
            country?: string;
            /** @example Central Vietnam */
            region?: string;
            /** @example Ancient port town in Central Vietnam. */
            descriptionEn?: string;
            /** @example Phố cổ ven sông ở miền Trung Việt Nam. */
            descriptionVi?: string;
            /**
             * @default true
             * @example true
             */
            isActive: boolean;
            media?: components["schemas"]["MediaInputDto"][];
        };
        UpdateDestinationDto: {
            /**
             * @description Any format — normalized server-side to kebab-case (max 80). Omit to generate from nameEn.
             * @example hoi-an
             */
            slug?: string;
            /** @example Hoi An */
            nameEn?: string;
            /** @example Hội An */
            nameVi?: string;
            /** @example Vietnam */
            country?: string;
            /** @example Central Vietnam */
            region?: string;
            /** @example Ancient port town in Central Vietnam. */
            descriptionEn?: string;
            /** @example Phố cổ ven sông ở miền Trung Việt Nam. */
            descriptionVi?: string;
            /**
             * @default true
             * @example true
             */
            isActive: boolean;
            media?: components["schemas"]["MediaInputDto"][];
        };
        TourWithStatsDto: {
            /** Format: uuid */
            id: string;
            /** @example phu-quoc-sunset-cruise */
            slug: string;
            titleEn: string;
            titleVi: string;
            summaryEn: string | null;
            summaryVi: string | null;
            /** Format: uuid */
            destinationId: string;
            /** @example 3 */
            durationDays: number;
            /** @example 20 */
            maxGroupSize: number;
            /**
             * @description Decimal serialised as string
             * @example 199.00
             */
            basePrice: string;
            /** @example USD */
            currency: string;
            /**
             * @example PACKAGE
             * @enum {string}
             */
            category: "DAY" | "PACKAGE" | "CUSTOM" | "HONEYMOON" | "MUSICAL";
            difficulty: string | null;
            isPublished: boolean;
            isFeatured: boolean;
            /**
             * @example [
             *       "Hotel",
             *       "Breakfast"
             *     ]
             */
            included: string[];
            /**
             * @example [
             *       "Flights",
             *       "Tips"
             *     ]
             */
            excluded: string[];
            meetingPoint: string | null;
            /** @description Cloudinary-backed media (hero/gallery/video). */
            media: components["schemas"]["MediaItemDto"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /**
             * @description Mean of approved-only review ratings; null when none
             * @example 4.6
             */
            averageRating: number | null;
            /**
             * @description Count of approved reviews
             * @example 18
             */
            reviewsCount: number;
            /**
             * @description Total seatsBooked across the tour departures
             * @example 124
             */
            peopleGoing: number;
        };
        PaginatedToursDto: {
            items: components["schemas"]["TourWithStatsDto"][];
            meta: components["schemas"]["ApiMetaDto"];
        };
        ItineraryDayDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tourId: string;
            /** @example 1 */
            dayNumber: number;
            titleEn: string;
            titleVi: string;
            descriptionEn: string | null;
            descriptionVi: string | null;
        };
        TourDetailDto: {
            /** Format: uuid */
            id: string;
            /** @example phu-quoc-sunset-cruise */
            slug: string;
            titleEn: string;
            titleVi: string;
            summaryEn: string | null;
            summaryVi: string | null;
            /** Format: uuid */
            destinationId: string;
            /** @example 3 */
            durationDays: number;
            /** @example 20 */
            maxGroupSize: number;
            /**
             * @description Decimal serialised as string
             * @example 199.00
             */
            basePrice: string;
            /** @example USD */
            currency: string;
            /**
             * @example PACKAGE
             * @enum {string}
             */
            category: "DAY" | "PACKAGE" | "CUSTOM" | "HONEYMOON" | "MUSICAL";
            difficulty: string | null;
            isPublished: boolean;
            isFeatured: boolean;
            /**
             * @example [
             *       "Hotel",
             *       "Breakfast"
             *     ]
             */
            included: string[];
            /**
             * @example [
             *       "Flights",
             *       "Tips"
             *     ]
             */
            excluded: string[];
            meetingPoint: string | null;
            /** @description Cloudinary-backed media (hero/gallery/video). */
            media: components["schemas"]["MediaItemDto"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /**
             * @description Mean of approved-only review ratings; null when none
             * @example 4.6
             */
            averageRating: number | null;
            /**
             * @description Count of approved reviews
             * @example 18
             */
            reviewsCount: number;
            /**
             * @description Total seatsBooked across the tour departures
             * @example 124
             */
            peopleGoing: number;
            destination: components["schemas"]["DestinationDto"];
            itinerary: components["schemas"]["ItineraryDayDto"][];
        };
        TourDto: {
            /** Format: uuid */
            id: string;
            /** @example phu-quoc-sunset-cruise */
            slug: string;
            titleEn: string;
            titleVi: string;
            summaryEn: string | null;
            summaryVi: string | null;
            /** Format: uuid */
            destinationId: string;
            /** @example 3 */
            durationDays: number;
            /** @example 20 */
            maxGroupSize: number;
            /**
             * @description Decimal serialised as string
             * @example 199.00
             */
            basePrice: string;
            /** @example USD */
            currency: string;
            /**
             * @example PACKAGE
             * @enum {string}
             */
            category: "DAY" | "PACKAGE" | "CUSTOM" | "HONEYMOON" | "MUSICAL";
            difficulty: string | null;
            isPublished: boolean;
            isFeatured: boolean;
            /**
             * @example [
             *       "Hotel",
             *       "Breakfast"
             *     ]
             */
            included: string[];
            /**
             * @example [
             *       "Flights",
             *       "Tips"
             *     ]
             */
            excluded: string[];
            meetingPoint: string | null;
            /** @description Cloudinary-backed media (hero/gallery/video). */
            media: components["schemas"]["MediaItemDto"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateTourDto: {
            /**
             * @description Any format — normalized server-side to kebab-case (max 120). Omit to generate from titleEn.
             * @example hoi-an-walking-tour
             */
            slug?: string;
            /** @example Hoi An Ancient Town Walking Tour */
            titleEn: string;
            /** @example Tour bộ phố cổ Hội An */
            titleVi: string;
            /** @example Half-day stroll through lantern-lit alleys. */
            summaryEn?: string;
            /** @example Tour nửa ngày qua các con hẻm đèn lồng. */
            summaryVi?: string;
            /**
             * @description UUID of an existing destination
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            destinationId: string;
            /** @example 1 */
            durationDays: number;
            /**
             * @default 20
             * @example 20
             */
            maxGroupSize: number;
            /** @example Hoi An tourist info centre, 78 Le Loi street */
            meetingPoint?: string;
            /** @example 49.5 */
            basePrice: number;
            /** @example USD */
            currency?: string;
            /**
             * @default DAY
             * @enum {string}
             */
            category: "DAY" | "PACKAGE" | "CUSTOM" | "HONEYMOON" | "MUSICAL";
            /** @example easy */
            difficulty?: string;
            /**
             * @default false
             * @example false
             */
            isPublished: boolean;
            /**
             * @default false
             * @example false
             */
            isFeatured: boolean;
            /**
             * @example [
             *       "Local guide",
             *       "Bottled water",
             *       "Lunch"
             *     ]
             */
            included?: string[];
            /**
             * @example [
             *       "Personal expenses",
             *       "Tips"
             *     ]
             */
            excluded?: string[];
            media?: components["schemas"]["MediaInputDto"][];
        };
        UpdateTourDto: {
            /**
             * @description Any format — normalized server-side to kebab-case (max 120). Omit to generate from titleEn.
             * @example hoi-an-walking-tour
             */
            slug?: string;
            /** @example Hoi An Ancient Town Walking Tour */
            titleEn?: string;
            /** @example Tour bộ phố cổ Hội An */
            titleVi?: string;
            /** @example Half-day stroll through lantern-lit alleys. */
            summaryEn?: string;
            /** @example Tour nửa ngày qua các con hẻm đèn lồng. */
            summaryVi?: string;
            /**
             * @description UUID of an existing destination
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            destinationId?: string;
            /** @example 1 */
            durationDays?: number;
            /**
             * @default 20
             * @example 20
             */
            maxGroupSize: number;
            /** @example Hoi An tourist info centre, 78 Le Loi street */
            meetingPoint?: string;
            /** @example 49.5 */
            basePrice?: number;
            /** @example USD */
            currency?: string;
            /**
             * @default DAY
             * @enum {string}
             */
            category: "DAY" | "PACKAGE" | "CUSTOM" | "HONEYMOON" | "MUSICAL";
            /** @example easy */
            difficulty?: string;
            /**
             * @default false
             * @example false
             */
            isPublished: boolean;
            /**
             * @default false
             * @example false
             */
            isFeatured: boolean;
            /**
             * @example [
             *       "Local guide",
             *       "Bottled water",
             *       "Lunch"
             *     ]
             */
            included?: string[];
            /**
             * @example [
             *       "Personal expenses",
             *       "Tips"
             *     ]
             */
            excluded?: string[];
            media?: components["schemas"]["MediaInputDto"][];
        };
        CreateItineraryDayDto: {
            /** @example 1 */
            dayNumber: number;
            /** @example Arrival & Old Town Walk */
            titleEn: string;
            /** @example Đón khách & Tham quan phố cổ */
            titleVi: string;
            /** @example Pick up at hotel, evening stroll through lantern-lit streets. */
            descriptionEn?: string;
            /** @example Đón tại khách sạn, tản bộ buổi tối qua các con phố đèn lồng. */
            descriptionVi?: string;
        };
        UpdateItineraryDayDto: {
            /** @example 1 */
            dayNumber?: number;
            /** @example Arrival & Old Town Walk */
            titleEn?: string;
            /** @example Đón khách & Tham quan phố cổ */
            titleVi?: string;
            /** @example Pick up at hotel, evening stroll through lantern-lit streets. */
            descriptionEn?: string;
            /** @example Đón tại khách sạn, tản bộ buổi tối qua các con phố đèn lồng. */
            descriptionVi?: string;
        };
        DepartureDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tourId: string;
            /**
             * Format: date
             * @example 2026-09-12
             */
            startDate: string;
            /**
             * Format: date
             * @example 2026-09-15
             */
            endDate: string;
            /**
             * @description Decimal serialised as string; null = use tour basePrice
             * @example 249.00
             */
            priceOverride: string | null;
            /** @example 20 */
            seatsTotal: number;
            /** @example 7 */
            seatsBooked: number;
            /**
             * @example OPEN
             * @enum {string}
             */
            status: "OPEN" | "CLOSED" | "CANCELLED";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateDepartureDto: {
            /**
             * @description ISO 8601 date
             * @example 2026-08-15
             */
            startDate: string;
            /**
             * @description ISO 8601 date
             * @example 2026-08-15
             */
            endDate: string;
            /** @example 15 */
            seatsTotal: number;
            /** @example 59 */
            priceOverride?: number;
            /**
             * @default OPEN
             * @enum {string}
             */
            status: "OPEN" | "CLOSED" | "CANCELLED";
        };
        UpdateDepartureDto: {
            /**
             * @description ISO 8601 date
             * @example 2026-08-15
             */
            startDate?: string;
            /**
             * @description ISO 8601 date
             * @example 2026-08-15
             */
            endDate?: string;
            /** @example 15 */
            seatsTotal?: number;
            /** @example 59 */
            priceOverride?: number;
            /**
             * @default OPEN
             * @enum {string}
             */
            status: "OPEN" | "CLOSED" | "CANCELLED";
        };
        CreateSignedUploadUrlDto: {
            /**
             * @description Upload classification — determines the storage folder + future RLS scope.
             * @enum {string}
             */
            purpose: "TOUR_HERO" | "TOUR_GALLERY" | "TOUR_VIDEO" | "DESTINATION_HERO" | "DESTINATION_VIDEO" | "USER_AVATAR";
            /**
             * @description Original filename (single extension). The backend sanitizes + timestamps it before persisting.
             * @example hero-shot.jpg
             */
            filename: string;
            /** @example image/jpeg */
            contentType?: string;
        };
        CreateBookingDto: {
            /**
             * @description Slug of an existing published tour (kebab-case).
             * @example hoi-an-walking-tour
             */
            tourSlug: string;
            /**
             * @description UUID of a departure under the tour. Must be OPEN.
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            departureId: string;
            /** @example 2 */
            numAdults: number;
            /**
             * @default 0
             * @example 1
             */
            numChildren: number;
            /** @example Nguyen Van A */
            contactName: string;
            /** @example guest@example.com */
            contactEmail: string;
            /** @example +84901234567 */
            contactPhone?: string;
            /** @example Vegetarian meals for one adult. */
            specialRequests?: string;
        };
        CreateBookingResponseDto: {
            /** @example BK-7K3F92 */
            bookingCode: string;
            /**
             * Format: uri
             * @description Redirect the browser here to complete payment
             * @example https://checkout.stripe.com/c/pay/cs_test_xxx
             */
            checkoutUrl: string;
        };
        BookingTourSummaryDto: {
            /** @example sa-pa-trek-2d1n */
            slug: string;
            /** @example Sapa Rice Terrace Trek (2D1N Homestay) */
            titleEn: string;
            /** @example Trekking ruộng bậc thang Sa Pa (2N1Đ homestay) */
            titleVi: string;
        };
        BookingDepartureSummaryDto: {
            /**
             * Format: date
             * @example 2026-09-12
             */
            startDate: string;
            /**
             * Format: date
             * @example 2026-09-15
             */
            endDate: string;
            /**
             * @description Present on GET /bookings/:code; omitted on GET /bookings/me
             * @example OPEN
             * @enum {string}
             */
            status?: "OPEN" | "CLOSED" | "CANCELLED";
        };
        BookingDto: {
            /** Format: uuid */
            id: string;
            /** @example BK-7K3F92 */
            code: string;
            /** Format: uuid */
            userId: string;
            /** Format: uuid */
            tourId: string;
            /** Format: uuid */
            departureId: string;
            /** @example 2 */
            numAdults: number;
            /** @example 1 */
            numChildren: number;
            /**
             * @description Decimal serialised as string
             * @example 597.00
             */
            totalAmount: string;
            /** @example USD */
            currency: string;
            /**
             * @example PENDING
             * @enum {string}
             */
            status: "PENDING" | "PAID" | "CANCELLED" | "REFUNDED";
            contactName: string;
            /** Format: email */
            contactEmail: string;
            contactPhone: string | null;
            specialRequests: string | null;
            stripeSessionId: string | null;
            stripePaymentIntentId: string | null;
            /** Format: date-time */
            paidAt: string | null;
            /** Format: date-time */
            cancelledAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            tour: components["schemas"]["BookingTourSummaryDto"];
            departure: components["schemas"]["BookingDepartureSummaryDto"];
        };
        RefundBookingDto: {
            /**
             * @description Optional human-readable reason logged with Stripe metadata.
             * @example Tour cancelled due to weather
             */
            reason?: string;
        };
        CreateReviewDto: {
            /**
             * @description Booking code that this review is attached to (must be PAID).
             * @example BK-ABCDEFGH
             */
            bookingCode: string;
            /**
             * @description 1–5 stars
             * @example 5
             */
            rating: number;
            /** @example Unforgettable trip */
            title?: string;
            /**
             * @description Review body — 10 to 2000 chars.
             * @example Guide was excellent and the itinerary was well paced...
             */
            body: string;
        };
        ReviewDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tourId: string;
            /** Format: uuid */
            userId: string;
            /** Format: uuid */
            bookingId: string;
            /** @example 5 */
            rating: number;
            title: string | null;
            body: string;
            isApproved: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PublicReviewDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tourId: string;
            /** Format: uuid */
            userId: string;
            /** Format: uuid */
            bookingId: string;
            /** @example 5 */
            rating: number;
            title: string | null;
            body: string;
            isApproved: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** @description Reviewer's full name (null if not set) */
            userFullName: string | null;
        };
        PaginatedPublicReviewsDto: {
            items: components["schemas"]["PublicReviewDto"][];
            meta: components["schemas"]["ApiMetaDto"];
        };
        ModerateReviewDto: {
            /**
             * @description true to approve and publish; false to revert to draft.
             * @example true
             */
            isApproved: boolean;
        };
        WishlistItemDto: {
            /** Format: uuid */
            userId: string;
            /** Format: uuid */
            tourId: string;
            /** Format: date-time */
            createdAt: string;
            /** @description Joined tour payload (includes Figma stats) */
            tour: components["schemas"]["TourWithStatsDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_syncCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncUserDto"];
            };
        };
        responses: {
            /** @description User upserted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description Missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_syncAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncUserDto"];
            };
        };
        responses: {
            /** @description User upserted as ADMIN */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description Missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email not on admin allowlist */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description Missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not yet synced — call /auth/sync first */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeDto"];
            };
        };
        responses: {
            /** @description Updated profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description Missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DestinationsController_list: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                search?: string;
                isActive?: boolean;
                sortBy?: "createdAt" | "updatedAt" | "nameEn" | "nameVi";
                sortOrder?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated destinations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDestinationsDto"];
                };
            };
        };
    };
    DestinationsController_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Destination */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DestinationDto"];
                };
            };
            /** @description Slug not found or inactive */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminDestinationsController_list: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                search?: string;
                isActive?: boolean;
                sortBy?: "createdAt" | "updatedAt" | "nameEn" | "nameVi";
                sortOrder?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated destinations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDestinationsDto"];
                };
            };
            /** @description Missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not an ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminDestinationsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDestinationDto"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DestinationDto"];
                };
            };
            /** @description Slug already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminDestinationsController_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Destination */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DestinationDto"];
                };
            };
            /** @description Slug not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminDestinationsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted (echo) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DestinationDto"];
                };
            };
            /** @description Slug not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Destination still has tours referencing it */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminDestinationsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDestinationDto"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DestinationDto"];
                };
            };
            /** @description Slug not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description New slug already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ToursController_list: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                /** @description Destination slug (kebab-case) */
                destination?: string;
                category?: "DAY" | "PACKAGE" | "CUSTOM" | "HONEYMOON" | "MUSICAL";
                minPrice?: number;
                maxPrice?: number;
                duration?: number;
                featured?: boolean;
                q?: string;
                sortBy?: "createdAt" | "basePrice" | "durationDays" | "titleEn";
                sortOrder?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated tours */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedToursDto"];
                };
            };
        };
    };
    ToursController_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tour with destination + itinerary + stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TourDetailDto"];
                };
            };
            /** @description Slug not found or unpublished */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminToursController_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tour */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TourDto"];
                };
            };
            /** @description Slug not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminToursController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted (echo) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TourDto"];
                };
            };
            /** @description Slug not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Tour still has bookings referencing it */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminToursController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTourDto"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TourDto"];
                };
            };
            /** @description Invalid destinationId */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Slug not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description New slug already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminToursController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTourDto"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TourDto"];
                };
            };
            /** @description Invalid destinationId */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Slug already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminItineraryController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Days ordered by dayNumber asc */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItineraryDayDto"][];
                };
            };
            /** @description Tour slug not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminItineraryController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateItineraryDayDto"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItineraryDayDto"];
                };
            };
            /** @description Tour slug not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Day number already exists for this tour */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminItineraryController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                dayNumber: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted (echo) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItineraryDayDto"];
                };
            };
            /** @description Tour or day not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminItineraryController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                dayNumber: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateItineraryDayDto"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItineraryDayDto"];
                };
            };
            /** @description Tour or day not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Renumber collision */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DeparturesController_list: {
        parameters: {
            query?: {
                /** @description ISO 8601 date */
                from?: string;
                /** @description ISO 8601 date */
                to?: string;
                status?: "OPEN" | "CLOSED" | "CANCELLED";
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Departures ordered by startDate asc */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartureDto"][];
                };
            };
            /** @description Tour slug not found or unpublished */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminDeparturesController_list: {
        parameters: {
            query?: {
                /** @description ISO 8601 date */
                from?: string;
                /** @description ISO 8601 date */
                to?: string;
                status?: "OPEN" | "CLOSED" | "CANCELLED";
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Departures ordered by startDate asc */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartureDto"][];
                };
            };
            /** @description Tour slug not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminDeparturesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDepartureDto"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartureDto"];
                };
            };
            /** @description Invalid date range */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Tour slug not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminDeparturesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted (echo) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartureDto"];
                };
            };
            /** @description Tour or departure not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Departure has bookings */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminDeparturesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDepartureDto"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartureDto"];
                };
            };
            /** @description Invalid date range or seatsTotal below seatsBooked */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Tour or departure not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminUploadsController_createSignedUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSignedUploadUrlDto"];
            };
        };
        responses: {
            /** @description Signed upload params envelope */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request body or format */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PaymentsController_handle: {
        parameters: {
            query?: never;
            header: {
                "stripe-signature": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event processed or ignored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Signature verification failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BookingsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingDto"];
            };
        };
        responses: {
            /** @description Created + checkout URL minted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateBookingResponseDto"];
                };
            };
            /** @description Departure not OPEN */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not synced */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Tour or departure not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No seats available */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BookingsController_listOwn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bookings with tour + departure joined */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDto"][];
                };
            };
            /** @description User not synced */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BookingsController_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Booking detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDto"];
                };
            };
            /** @description User not synced */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Booking not found or not owned */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminBookingsController_refund: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefundBookingDto"];
            };
        };
        responses: {
            /** @description Booking REFUNDED + seats released */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDto"];
                };
            };
            /** @description Not refundable or Stripe failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing/invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Caller is not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Booking not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReviewsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReviewDto"];
            };
        };
        responses: {
            /** @description Created (pending approval) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewDto"];
                };
            };
            /** @description Booking not PAID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not synced */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not the owner of the booking */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Booking not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Booking already has a review */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PublicReviewsController_list: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated approved reviews */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPublicReviewsDto"];
                };
            };
            /** @description Tour slug not found or unpublished */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminReviewsController_moderate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModerateReviewDto"];
            };
        };
        responses: {
            /** @description Updated review row */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewDto"];
                };
            };
            /** @description Missing/invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Caller is not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Review not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WishlistController_add: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tourId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wishlist row (created or existing) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WishlistItemDto"];
                };
            };
            /** @description User not synced */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Tour not found or unpublished */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WishlistController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tourId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed (or already absent) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not synced */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WishlistController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of wishlist rows + tour */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WishlistItemDto"][];
                };
            };
            /** @description User not synced */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminStatsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregated stats payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing/invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Caller is not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
